#include "header.typ"

#include "sections/01-cover.typ"
#include "sections/02-version-log.typ"
#include "sections/03-collaboration-insights.typ"
#include "sections/04-student-outcome.typ"
#include "sections/05-table-of-contents.typ"
#include "sections/06-smart-goals.typ"
#include "sections/07-startup-profile.typ"
#include "sections/08-solution-profile.typ"
#include "sections/09-target-segments.typ"
#include "sections/10-competitors.typ"
#include "sections/11-interviews.typ"
#include "sections/12-needfinding.typ"
#include "sections/13-requirements-specification.typ"
#include "sections/14-strategic-domain-driven-design.typ"
#include "sections/15-tactical-domain-driven-design.typ"
